import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";

import Link from 'next/link';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const san = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next JS FullStack Books",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={san.className}>
        <div className="min-h-screen h-auto bg-background p-5">
          {/* <Link href="/">
            <img src="/img/logo.png" className="w-full" alt="eSewa" />
          </Link> */}
          <ToastContainer />
          {children}
        </div>
      </body>
    </html>
  );
}
